require 'pry'
require 'nokogiri'
require 'open-uri'
require 'terminal-table'

require_relative '../lib/local_ski_report/formattable'
require_relative '../lib/local_ski_report/regions'
require_relative '../lib/local_ski_report/output'
require_relative '../lib/local_ski_report/report'
require_relative '../lib/local_ski_report/resort'
require_relative '../lib/local_ski_report/scraper'
require_relative '../lib/local_ski_report/cli'
