require 'pry'
require 'artii'
require 'nokogiri'
require 'chromedriver-helper'
require 'watir'
require 'headless'
require 'open-uri'
require 'terminal-table'
require 'require_all'

require_all 'lib/**/*.rb'
